[files]
extend-exclude = []

[default]

[default.extend-words]
# <typo> = "<correction>"

[default.extend-identifiers]
FO = "FO"
BA = "BA"
ABL = "ABL"
ND = "ND"
recal = "recal"
PN = "PN"
sampe = "sampe"
CAF = "CAF"
ALLs = "ALLs"
Alls = "ALLs"

