#!/bin/bash

cd /cromwell_root
tmpDir=$(mkdir -p "/cromwell_root/clays-cromwell-bucket/cromwell-execution/rnaseq_standard/9795b8f3-827e-4570-b5c7-990fedfee29e/call-compute_checksum/tmp.f2b537a1" && echo "/cromwell_root/clays-cromwell-bucket/cromwell-execution/rnaseq_standard/9795b8f3-827e-4570-b5c7-990fedfee29e/call-compute_checksum/tmp.f2b537a1")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell_root

)
out9795b8f3="${tmpDir}/out.$$" err9795b8f3="${tmpDir}/err.$$"
mkfifo "$out9795b8f3" "$err9795b8f3"
trap 'rm "$out9795b8f3" "$err9795b8f3"' EXIT
tee '/cromwell_root/compute_checksum-stdout.log' < "$out9795b8f3" &
tee '/cromwell_root/compute_checksum-stderr.log' < "$err9795b8f3" >&2 &
(
cd /cromwell_root


md5sum /cromwell_root/clays-cromwell-bucket/cromwell-execution/rnaseq_standard/9795b8f3-827e-4570-b5c7-990fedfee29e/call-alignment/Sample.Aligned.sortedByCoord.out.bam > s3://clays-cromwell-bucket/cromwell-execution/rnaseq_standard/9795b8f3-827e-4570-b5c7-990fedfee29e/call-alignment/Sample.Aligned.sortedByCoord.out.bam.md5
)  > "$out9795b8f3" 2> "$err9795b8f3"
echo $? > /cromwell_root/compute_checksum-rc.txt.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell_root
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell_root
sync


)
mv /cromwell_root/compute_checksum-rc.txt.tmp /cromwell_root/compute_checksum-rc.txt
