version 1.2

task somatic {
    meta {
        description: "Run Strelka somatic variant calling workflow"
        outputs: {
            strelka_output: "Directory containing Strelka somatic variant calls",
            somatic_indels: "VCF file with somatic indels",
            somatic_indels_index: "Index file for the somatic indels VCF",
            somatic_snvs: "VCF file with somatic SNVs",
            somatic_snvs_index: "Index file for the somatic SNVs VCF",
            log_file: "Log file from the Strelka workflow execution",
        }
    }

    parameter_meta {
        reference_fasta: "Reference genome in FASTA format"
        reference_fasta_index: "Index file for the reference genome FASTA"
        normal_bam: "Input BAM file with aligned reads for normal sample"
        normal_bam_index: "Index file for the normal BAM file"
        tumor_bam: "Input BAM file with aligned reads for tumor sample"
        tumor_bam_index: "Index file for the tumor BAM file"
        indel_candidates: "Optional VCF file with candidate indels, recommended to be generated by Manta"
        indel_candidates_index: "Index file for the indel candidates VCF"
        output_dir: "Directory to store Strelka output"
        exome: "Boolean indicating if the data is exome sequencing"
        rna: "Boolean indicating if the data is RNA sequencing"
        threads: "Number of threads to use"
        modify_disk_size_gb: "Additional disk size in GB to allocate"
    }

    input {
        File reference_fasta
        File reference_fasta_index
        File normal_bam
        File normal_bam_index
        File tumor_bam
        File tumor_bam_index
        File? indel_candidates
        #@ except: UnusedInput
        File? indel_candidates_index
        String output_dir = "strelka_somatic_output"
        Boolean exome = false
        Boolean rna = false
        Int threads = 4
        Int modify_disk_size_gb = 0
    }

    Int disk_size_gb = ceil(size(reference_fasta, "GB") * 2) + ceil(size(normal_bam, "GB")
        * 2) + ceil(size(tumor_bam, "GB") * 2) + (if defined(indel_candidates)
        then ceil(size(indel_candidates, "GB"))
        else 0
    ) + 20 + modify_disk_size_gb

    String tumor = basename(tumor_bam)
    String normal = basename(normal_bam)

    command <<<
        set -euo pipefail

        ref_fasta=~{basename(reference_fasta, ".gz")}
        gunzip -c "~{reference_fasta}" > "$ref_fasta" \
            || ln -sf "~{reference_fasta}" "$ref_fasta"
        ln -sf "~{reference_fasta_index}" "$ref_fasta.fai"

        ln -sf "~{tumor_bam}" "~{tumor}"
        ln -sf "~{tumor_bam_index}" "~{tumor}.bai"
        ln -sf "~{normal_bam}" "~{normal}"
        ln -sf "~{normal_bam_index}" "~{normal}.bai"

        configureStrelkaSomaticWorkflow.py \
            --referenceFasta "$ref_fasta" \
            --runDir "~{output_dir}" \
            --tumorBam "~{tumor}" \
            --normalBam "~{normal}" \
            ~{if (exome)
                then "--exome"
                else ""
            } \
            ~{if (rna)
                then "--rna"
                else ""
            } \
            ~{(if (defined(indel_candidates))
                then "--indelCandidates '~{indel_candidates}'"
                else ""
            )}


        "~{output_dir}/runWorkflow.py" -m local -j ~{threads}

        rm -rf "$ref_fasta" "$ref_fasta.fai" "~{tumor}" "~{tumor}.bai" "~{normal}" "~{
            normal
        }.bai"
    >>>

    output {
        Directory strelka_output = output_dir
        File somatic_indels = "~{output_dir}/results/variants/somatic.indels.vcf.gz"
        File somatic_indels_index = "~{output_dir}/results/variants/somatic.indels.vcf.gz.tbi"
        File somatic_snvs = "~{output_dir}/results/variants/somatic.snvs.vcf.gz"
        File somatic_snvs_index = "~{output_dir}/results/variants/somatic.snvs.vcf.gz.tbi"
        File log_file = "~{output_dir}/workspace/pyflow.data/logs/pyflow_log.txt"
    }

    requirements {
        container: "quay.io/biocontainers/strelka:2.9.10--h9ee0642_1"
        cpu: threads
        memory: "25 GB"
        disks: "~{disk_size_gb} GB"
    }
}

task germline {
    meta {
        description: "Run Strelka germline variant calling workflow"
        outputs: {
            strelka_output: "Directory containing Strelka germline variant calls",
            log_file: "Log file from the Strelka workflow execution",
        }
    }

    parameter_meta {
        reference_fasta: "Reference genome in FASTA format"
        reference_fasta_index: "Index file for the reference genome FASTA"
        bam: "Input BAM file with aligned reads"
        bam_index: "Index for input BAM file"
        output_dir: "Directory to store Strelka output"
        exome: "Boolean indicating if the data is exome sequencing"
        rna: "Boolean indicating if the data is RNA sequencing"
        threads: "Number of threads to use"
        modify_disk_size_gb: "Additional disk size in GB to allocate"
    }

    input {
        File reference_fasta
        File reference_fasta_index
        File bam
        File bam_index
        String output_dir = "strelka_germline_output"
        Boolean exome = false
        Boolean rna = false
        Int threads = 4
        Int modify_disk_size_gb = 0
    }

    Int disk_size_gb = ceil(size(reference_fasta, "GB") * 2) + ceil(size(bam, "GB") * 2) + 20
        + modify_disk_size_gb

    String filename = basename(bam)

    command <<<
        set -euo pipefail

        ref_fasta=~{basename(reference_fasta, ".gz")}
        gunzip -c "~{reference_fasta}" > "$ref_fasta" \
            || ln -sf "~{reference_fasta}" "$ref_fasta"
        ln -sf "~{reference_fasta_index}" "$ref_fasta.fai"

        ln -sf "~{bam}" "~{filename}"
        ln -sf "~{bam_index}" "~{filename}.bai"

        configureStrelkaGermlineWorkflow.py \
            --referenceFasta "$ref_fasta" \
            --runDir "~{output_dir}" \
            --bam "~{filename}" \
            ~{if (exome)
                then "--exome"
                else ""
            } \
            ~{if (rna)
                then "--rna"
                else ""
            }

        "~{output_dir}/runWorkflow.py" -m local -j ~{threads}

        rm -rf "$ref_fasta" "$ref_fasta.fai" "~{filename}" "~{filename}.bai" "~{output_dir
        }/workspace/pyflow.data/logs/tmp"
    >>>

    output {
        Directory strelka_output = output_dir
        File log_file = "~{output_dir}/workspace/pyflow.data/logs/pyflow_log.txt"
    }

    requirements {
        container: "quay.io/biocontainers/strelka:2.9.10--h9ee0642_1"
        cpu: threads
        memory: "25 GB"
        disks: "~{disk_size_gb} GB"
    }
}
