name: Build and Test

on:
    push:

jobs:
    call-build:
        uses: ./.github/workflows/docker-build.yaml
        secrets: inherit
    call-test:
        uses: ./.github/workflows/pytest.yaml
        needs: call-build
