name: Workflows Miniwdl Check

on: [push]

jobs:
  miniwdl_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install miniwdl
      run: |
        python -m pip install --upgrade pip
        pip install miniwdl
    - name: Run miniwdl
      run: |
        EXITCODE=0
        echo "Checking WDL files using \`miniwdl check\`."
        shopt -s extglob
        files=$(find ./!(template) -name '*.wdl')
        for file in $files; do
          echo "  [***] $file [***]"
          miniwdl check "$file"
          EXITCODE=$(($? || EXITCODE))
        done
        exit $EXITCODE
