name: pytest-workflow test

on: [push]

jobs:
  pytest_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install miniwdl and pytest-workflow
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: pull image
      run: |
        docker pull quay.io/biocontainers/gtfparse:2.5.0--pyh7cba7a3_0 &&
        docker pull quay.io/biocontainers/gtfparse:1.2.1--pyh864c0ab_0
    - name: filter tests
      run: | 
        find tests -name '*.yaml'| grep -v 'test_util.yaml' | xargs rm &&
        find tests -name '*.yaml' -exec yq --output-format yaml -i 'del(.[] | select(.tags[] | test("reference|deprecated|cellranger") ) )' {} \;
    - name: Run pytest-workflow
      run: |
        pytest --git-aware --basetemp /home/runner/work/pytest --symlink