name: Workflows Sprocket Lint

on: [push]

jobs:
  sprocket_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run 'sprocket lint'
      uses: stjude-rust-labs/sprocket-action@main
      with:
        lint: true
        except: KnownRules
        exclusions: methylation
    - name: Run 'sprocket format'
      uses: stjude-rust-labs/sprocket-action@feat/format
      with:
        action: format
