name: Sprocket Test

on:
  workflow_call:

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
        files: ${{ steps.set-files.outputs.files }}
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: set files
          id: set-files
          run: echo "files=$(find . -name '*.wdl' -print -o -path "./template" -prune | jq -ncR '[inputs]')" >> $GITHUB_OUTPUT
  sprocket_test:
    needs: list-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.list-files.outputs.files) }}
        runner: [sprocket]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Install Sprocket
      run: |
        SPROCKET_URL=$(curl -sSL https://api.github.com/repos/stjude-rust-labs/sprocket/releases/latest \
          | jq -r '.assets[] | select(.name | test("x86_64-unknown-linux-gnu.tar.gz")) | .browser_download_url')
        curl -sSL "$SPROCKET_URL" | tar -xz -C /usr/local/bin sprocket
    - name: Update containers
      run: |
        ./developer_scripts/update_container_tags.sh ${GITHUB_REF##*/}
    - name: Run sprocket test
      env: 
        RUNNER: ${{ matrix.runner }}
      run: |
        sprocket dev test --filter-tag reference --filter-tag slow --filter-tag high_mem ${{ matrix.file }} || for file in $(ls test/runs/*/*/*/attempts/0/std*); do echo $file > /dev/stderr ; cat $file > /dev/stderr; done