name: Workflows Sprocket Check

on: [push]

jobs:
    sprocket_check:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run sprocket
          uses: stjude-rust-labs/sprocket-action@main
          with:
            exclude-patterns: template
